//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviantArt.Chat.Oberon.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviantArt.Chat.Oberon.Plugins.PluginResource", typeof(PluginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays information about the bot..
        /// </summary>
        internal static string About_Summary {
            get {
                return ResourceManager.GetString("About.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about
        ///about system
        ///about upttime.
        /// </summary>
        internal static string About_Usage {
            get {
                return ResourceManager.GetString("About.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the access level prileges for a command..
        /// </summary>
        internal static string Access_Summary {
            get {
                return ResourceManager.GetString("Access.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access [command] (Range 0 through 100)
        ///access [command] default
        ///&lt;b&gt;Example:&lt;/b&gt; !access ping 0
        ///&lt;b&gt;Example:&lt;/b&gt; !access ping 100.
        /// </summary>
        internal static string Access_Usage {
            get {
                return ResourceManager.GetString("Access.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds or removes a chatroom from the auto join list..
        /// </summary>
        internal static string Autojoin_Summary {
            get {
                return ResourceManager.GetString("Autojoin.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autojoin add [room]
        ///autojoin remove [room]
        ///autojoin list.
        /// </summary>
        internal static string Autojoin_Usage {
            get {
                return ResourceManager.GetString("Autojoin.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat rooms that the bot is currently signed into..
        /// </summary>
        internal static string Chats_Summary {
            get {
                return ResourceManager.GetString("Chats.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chats.
        /// </summary>
        internal static string Chats_Usage {
            get {
                return ResourceManager.GetString("Chats.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available commands and their access levels..
        /// </summary>
        internal static string Commands_Summary {
            get {
                return ResourceManager.GetString("Commands.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands - list of commands you have access to
        ///commands all - list all commands
        ///commands details - list all commands and show modules.
        /// </summary>
        internal static string Commands_Usage {
            get {
                return ResourceManager.GetString("Commands.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays credits..
        /// </summary>
        internal static string Credits_Summary {
            get {
                return ResourceManager.GetString("Credits.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        internal static string Credits_Usage {
            get {
                return ResourceManager.GetString("Credits.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily change the bot&apos;s trigger..
        /// </summary>
        internal static string CTrig_Summary {
            get {
                return ResourceManager.GetString("CTrig.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctrig [trigger]
        ///&lt;b&gt;Example:&lt;/b&gt; !ctrig #.
        /// </summary>
        internal static string CTrig_Usage {
            get {
                return ResourceManager.GetString("CTrig.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays help information about a particular command..
        /// </summary>
        internal static string Help_Summary {
            get {
                return ResourceManager.GetString("Help.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help [command].
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the bot join the provided chatroom..
        /// </summary>
        internal static string Join_Summary {
            get {
                return ResourceManager.GetString("Join.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join [room].
        /// </summary>
        internal static string Join_Usage {
            get {
                return ResourceManager.GetString("Join.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicks a user from a chatroom..
        /// </summary>
        internal static string Kick_Summary {
            get {
                return ResourceManager.GetString("Kick.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kick (room) [user]
        ///&lt;b&gt;Example:&lt;/b&gt; !kick botdom devartuser.
        /// </summary>
        internal static string Kick_Usage {
            get {
                return ResourceManager.GetString("Kick.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the users in a chatroom..
        /// </summary>
        internal static string List_Summary {
            get {
                return ResourceManager.GetString("List.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list [room].
        /// </summary>
        internal static string List_Usage {
            get {
                return ResourceManager.GetString("List.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the bot leave the provided chatroom..
        /// </summary>
        internal static string Part_Summary {
            get {
                return ResourceManager.GetString("Part.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part [room].
        /// </summary>
        internal static string Part_Usage {
            get {
                return ResourceManager.GetString("Part.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping the bot to find out how much lag it has..
        /// </summary>
        internal static string Ping_Summary {
            get {
                return ResourceManager.GetString("Ping.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ping.
        /// </summary>
        internal static string Ping_Usage {
            get {
                return ResourceManager.GetString("Ping.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to view plugin info, reload plugins, and turn plugins on or off..
        /// </summary>
        internal static string Plugins_Summary {
            get {
                return ResourceManager.GetString("Plugins.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins list - list all plugins loaded
        ///plugins reload - reload plugins
        ///plugins [plugin key] info - plugin information
        ///plugins [plugin key] turn [on or off] - turn plugin on or off
        ///&lt;b&gt;Exmaple:&lt;/b&gt; !plugins system info.
        /// </summary>
        internal static string Plugins_Usage {
            get {
                return ResourceManager.GetString("Plugins.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage bot priv class access levels..
        /// </summary>
        internal static string Priv_Summary {
            get {
                return ResourceManager.GetString("Priv.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priv [priv class] [level]
        ///&lt;b&gt;Example:&lt;/b&gt; !priv guest 1.
        /// </summary>
        internal static string Priv_Usage {
            get {
                return ResourceManager.GetString("Priv.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown the bot..
        /// </summary>
        internal static string Quit_Summary {
            get {
                return ResourceManager.GetString("Quit.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quit.
        /// </summary>
        internal static string Quit_Usage {
            get {
                return ResourceManager.GetString("Quit.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the bot..
        /// </summary>
        internal static string Restart_Summary {
            get {
                return ResourceManager.GetString("Restart.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        internal static string Restart_Usage {
            get {
                return ResourceManager.GetString("Restart.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have the bot say stuff..
        /// </summary>
        internal static string Say_Summary {
            get {
                return ResourceManager.GetString("Say.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say (#room) [message]
        ///&lt;b&gt;Example:&lt;/b&gt; !say #botdom Hi.
        /// </summary>
        internal static string Say_Usage {
            get {
                return ResourceManager.GetString("Say.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the current bot time..
        /// </summary>
        internal static string Time_Summary {
            get {
                return ResourceManager.GetString("Time.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string Time_Usage {
            get {
                return ResourceManager.GetString("Time.Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users registered to the bot..
        /// </summary>
        internal static string User_Summary {
            get {
                return ResourceManager.GetString("User.Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add [user] [level]
        ///edit [user] [level]
        ///list
        ///del [user]
        ///addprivclass [name] [level]
        ///delprivclass [name]
        ///&lt;b&gt;Example:&lt;/b&gt; !user add devartuser 50.
        /// </summary>
        internal static string User_Usage {
            get {
                return ResourceManager.GetString("User.Usage", resourceCulture);
            }
        }
    }
}
